#!/usr/bin/env python3
"""Speakrail token registry (v1.2, frozen) + tokenizer surgery + verification.

Event-driven calls; the LLM reads saved words + <complete> + silence markers,
and answers one decision token per call. Speak = Gemma's native turn-close (id 106), not a new token.

Ids 6..24 are Gemma's <unused0..18> slots: renamed in tokenizer.json and registered as specials, no vocab growth.
Ids 28..45 stay unused as spares (25 = <user_bc>, added in v1.1; 26-27 = <interject> </interject>, v1.2). Never reorder: a trained checkpoint's rows are bound to these ids.

vLLM 0.26 note: Gemma 4 has tied embeddings, and vLLM reads BOTH input and output
rows from embed_tokens and ignores the separate lm_head.weight in the w4a16-ct checkpoint. Export must still write
the trained rows into both tensors so HF / other loaders agree.
"""
from __future__ import annotations
import json, shutil, sys
from pathlib import Path

VOCAB_SIZE = 262144
TURN_CLOSE = 106          # native <turn|>: the "speak" decision, and the closer after a cut
TURN_OPEN = 105           # native <|turn>
TOOL_RESPONSE_OPEN = 50   # native <|tool_response> (also an EOS in generation_config)
CHANNEL_OPEN = 100        # native <|channel>: ban at serve time (logit_bias -100)

# (id, token, kind, init_text)
#   kind: "input"    written by the harness, saved in the context, never a loss target
#         "decision" a call's answer; loss target at call positions
#         "reserved" allocated for v2, not trained in v1
TOKENS = [
    (6,  "<complete>",     "input",    "the speaker has finished their turn"),
    (7,  "<sil:1s>",       "input",    "one second of silence"),
    (8,  "<sil:2s>",       "input",    "two seconds of silence"),
    (9,  "<sil:4s>",       "input",    "four seconds of silence"),
    (10, "<sil:8s>",       "input",    "eight seconds of silence"),
    (11, "<sil:16s>",      "input",    "sixteen seconds of silence"),
    (12, "<sil:32s>",      "input",    "thirty two seconds of silence"),
    (13, "<sil:64s>",      "input",    "about a minute of silence"),
    (14, "<sil:128s>",     "input",    "about two minutes of silence"),
    (15, "<sil:256s>",     "input",    "several minutes of silence"),
    (16, "<listen>",       "decision", "stay quiet and keep listening, ready to answer"),
    (17, "<listen_muted>", "decision", "stay silent, told to wait until allowed to speak"),
    (18, "<interrupt>",    "decision", "cut in now while the user is still speaking"),
    (19, "<continue>",     "decision", "that was only a backchannel, keep talking"),
    (20, "<yield>",        "decision", "stop talking, the user is taking the floor"),
    (21, "<bc>",           "reserved", "a short listener backchannel"),
    (22, "<bc_mm>",        "reserved", "mm-hmm"),
    (23, "<bc_yeah>",      "reserved", "yeah"),
    (24, "<bc_laugh>",     "reserved", "a short laugh"),
    # v1.1 (2026-09-25): acoustic user-backchannel hint from the turn head (P(backchannel) >= 0.95 on a frame)
    (25, "<user_bc>",      "input",    "the user just made a short listener sound like mm-hmm or yeah"),
    # v1.2: live tasks. The model says 1-4 words while the speaker keeps talking, without taking
    # the turn: <interject> is the decision (idle set), </interject> closes the words (a reply target, generated by the model)
    (26, "<interject>",    "decision", "say a few words now for the task the user set, without taking the turn"),
    (27, "</interject>",   "reply",    "end of the few words, the speaker goes on"),
]
VERSION = "v1.2"
USER_BC_THRESHOLD = 0.95
SPARE = (28, 45)
IDS = {t: i for i, t, _, _ in TOKENS}
SIL_LADDER_S = [1, 2, 4, 8, 16, 32, 64, 128, 256]
# Decision sets the harness passes as allowed_token_ids (TURN_CLOSE = speak).
IDLE_DECISIONS = [TURN_CLOSE, IDS["<interrupt>"], IDS["<listen>"], IDS["<listen_muted>"], IDS["<interject>"]]   # v1.2: + <interject>
OVERLAP_DECISIONS = [IDS["<continue>"], IDS["<yield>"], IDS["<listen>"]]


def sil_token(seconds: float) -> str | None:
    """Largest ladder marker <= seconds of silence (None below 1 s)."""
    best = None
    for s in SIL_LADDER_S:
        if seconds >= s: best = s
    return None if best is None else f"<sil:{best}s>"


def patch_tokenizer(src_dir: str, dst_dir: str) -> dict:
    src, dst = Path(src_dir), Path(dst_dir)
    if dst.exists(): raise FileExistsError(dst)
    dst.mkdir(parents=True)
    for f in ("tokenizer.json", "tokenizer_config.json", "chat_template.jinja", "special_tokens_map.json"):
        if (src / f).exists(): shutil.copy2(src / f, dst / f)
    tj = json.loads((dst / "tokenizer.json").read_text())
    vocab, added = tj["model"]["vocab"], tj["added_tokens"]
    inv = {v: k for k, v in vocab.items()}; added_ids = {a["id"] for a in added}
    n0 = len(vocab); mapped = []
    for tid, tok, kind, _ in TOKENS:
        old = inv.get(tid)
        if old is None or not old.startswith("<unused"): raise ValueError(f"id {tid} holds {old!r}, not an unused slot")
        if tid in added_ids: raise ValueError(f"id {tid} already a registered special")
        if tok in vocab: raise ValueError(f"{tok} already in vocab at {vocab[tok]}")
        del vocab[old]; vocab[tok] = tid
        added.append({"id": tid, "content": tok, "single_word": False, "lstrip": False, "rstrip": False,
                      "normalized": False, "special": True})
        mapped.append((tid, old, tok))
    added.sort(key=lambda a: a["id"])
    assert len(vocab) == n0, "vocab size changed"
    (dst / "tokenizer.json").write_text(json.dumps(tj, ensure_ascii=False))
    cfgp = dst / "tokenizer_config.json"
    if cfgp.exists():
        cfg = json.loads(cfgp.read_text())
        extra = list(cfg.get("additional_special_tokens", []) or [])
        cfg["additional_special_tokens"] = extra + [t for _, t, _, _ in TOKENS if t not in extra]
        cfgp.write_text(json.dumps(cfg, ensure_ascii=False, indent=1))
    registry = {"version": VERSION, "frozen": "2026-09-25", "user_bc_threshold": USER_BC_THRESHOLD, "vocab_size": VOCAB_SIZE, "spare_ids": list(SPARE),
                "native": {"turn_close_speak": TURN_CLOSE, "turn_open": TURN_OPEN,
                           "tool_response_open": TOOL_RESPONSE_OPEN, "channel_open_ban": CHANNEL_OPEN},
                "tokens": [{"id": i, "token": t, "kind": k, "init_text": x} for i, t, k, x in TOKENS],
                "idle_decisions": IDLE_DECISIONS, "overlap_decisions": OVERLAP_DECISIONS,
                "sil_ladder_s": SIL_LADDER_S}
    (dst / "tokens_v1.json").write_text(json.dumps(registry, indent=1))
    return {"vocab": n0, "mapped": mapped}


def verify(tok_dir: str, orig_dir: str, corpus: list[str]) -> dict:
    from tokenizers import Tokenizer
    from transformers import AutoTokenizer
    new, old = Tokenizer.from_file(f"{tok_dir}/tokenizer.json"), Tokenizer.from_file(f"{orig_dir}/tokenizer.json")
    probs = []
    for tid, t, _, _ in TOKENS:
        ids = new.encode(t, add_special_tokens=False).ids
        if ids != [tid]: probs.append(f"{t} -> {ids}")
        if new.decode([tid], skip_special_tokens=False) != t: probs.append(f"decode {tid} -> {new.decode([tid], skip_special_tokens=False)!r}")
    s = "so the standup is at ten<complete><sil:2s><listen>and then"
    ids = new.encode(s, add_special_tokens=False).ids
    for t in ("<complete>", "<sil:2s>", "<listen>"):
        if IDS[t] not in ids: probs.append(f"in-context {t} not split out: {ids}")
    diff = sum(new.encode(x, add_special_tokens=False).ids != old.encode(x, add_special_tokens=False).ids for x in corpus)
    if diff: probs.append(f"{diff}/{len(corpus)} ordinary texts tokenize differently")
    hf = AutoTokenizer.from_pretrained(tok_dir)
    for tid, t, _, _ in TOKENS:
        if hf.convert_tokens_to_ids(t) != tid: probs.append(f"HF maps {t} -> {hf.convert_tokens_to_ids(t)}")
    for name, tid in (("turn_close", TURN_CLOSE), ("turn_open", TURN_OPEN)):
        if hf.convert_ids_to_tokens(tid) not in ("<turn|>", "<|turn>"): probs.append(f"native {name} moved")
    return {"ok": not probs, "problems": probs, "corpus_checked": len(corpus), "in_context_ids": ids}


if __name__ == "__main__":
    # python tokens_v1.py <Gemma 4 tokenizer dir> <output dir>: write tokenizer v1.2 and verify it
    SRC, DST = sys.argv[1], sys.argv[2]
    print(patch_tokenizer(SRC, DST))
    corpus = ["so the standup is at ten, and then we ship.", "What's the weather like in Berlin right now?"]
    r = verify(DST, SRC, corpus); print(json.dumps(r, indent=1)); sys.exit(0 if r["ok"] else 1)
